version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/django_static
    app:
        restart: unless-stopped
        container_name: app
        build:
            context: .
            dockerfile: ./backend/docker/Dockerfile
        entrypoint: /app/docker/server-entrypoint.sh
        volumes:
            - static_volume:/app/backend/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: mysql
            MYSQL_HOST: db
            MYSQL_NAME: mydb
            MYSQL_USER: root
            MYSQL_PASSWORD: rootpassword
            MYSQL_PORT: 3306
        depends_on:
            - redis
            - db
    worker:
        restart: unless-stopped
        container_name: celery_worker
        build:
            context: .
            dockerfile: ./backend/docker/Dockerfile
        entrypoint: /app/docker/worker-entrypoint.sh
        volumes:
            - static_volume:/app/backend/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: mysql
            MYSQL_HOST: db
            MYSQL_NAME: mydb
            MYSQL_USER: root
            MYSQL_PASSWORD: rootpassword
            MYSQL_PORT: 3306
        ports:
            - 5555:5555   
        depends_on:
            - redis
            - db

    redis:
        container_name: redis
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379

    db:
        container_name: db
        restart: always
        build:
            context: .
            dockerfile: ./mysql/Dockerfile
        # image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
    
volumes:
    static_volume: {}
    postgres_data: {}
    mysql_data: {}